{% set name = "provenance" %}
{% set version = "0.14.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/provenance-{{ version }}.tar.gz
  sha256: 873f716e1e1a2b8550200bb9cd643460cc479144bceabcb42209bb3b1f8583d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - pip
    - python >=3.5

  run:
    - alembic >=0.9.1
    - boltons >=16.5.1
    - cloudpickle >=0.2.1
    - joblib >=0.15.0
    - memoized-property >=1.0.2
    - numpy
    - ordered-set >=2.0.1
    - psutil >=5.0.0
    - psycopg2
    - pyarrow
    - python >=3.5
    - s3fs >=0.0.9
    - sqlalchemy >=1.1.3
    - sqlalchemy-utils >=0.32.12
    - toolz >=0.8.2
    - wrapt >=1.10.8

test:
  imports:
    - provenance
    - provenance.sftp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bmabey/provenance
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Provenance and caching library for functions.
  dev_url: https://github.com/bmabey/provenance
  doc_url: https://provenance.readthedocs.io

extra:
  recipe-maintainers:
    - andersy005
    - bmabey
